//
// Created by alexander on 2019-08-15.
//

#ifndef CLION_TEST_SUMMER19_FAKETIMESERVICE_H
#define CLION_TEST_SUMMER19_FAKETIMESERVICE_H

#include "TimeService.h"

enum {TIME_UNKNOWN = -1};


#endif //CLION_TEST_SUMMER19_FAKETIMESERVICE_H
